(function(){
var h=null,k=!1,n=this;function p(a,b){var c=a.split("."),d=n;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&void 0!==b?d[f]=b:d=d[f]?d[f]:d[f]={}}
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function s(a){return"string"==typeof a}function t(a){var b=typeof a;return"object"==b&&a!=h||"function"==b}function u(a,b,c){return a.call.apply(a.bind,arguments)}
function v(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?u:v;return x.apply(h,arguments)}
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return x.apply(h,c)}return x(this,a)};function y(a){if(!aa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ba,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ca,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(da,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ea,"&quot;"));return a}var ba=/&/g,ca=/</g,da=/>/g,ea=/\"/g,aa=/[&<>\"]/;function fa(a){return Array.prototype.join.call(arguments,"")};var z=Array.prototype,A=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=c==h?0:0>c?Math.max(0,a.length+c):c;if(s(a))return!s(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},B=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=s(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function ga(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function ha(a,b,c){return 2>=arguments.length?z.slice.call(a,b):z.slice.call(a,b,c)};var C,D,E,F;function G(){return n.navigator?n.navigator.userAgent:h}F=E=D=C=k;var H;if(H=G()){var ia=n.navigator;C=0==H.indexOf("Opera");D=!C&&-1!=H.indexOf("MSIE");E=!C&&-1!=H.indexOf("WebKit");F=!C&&!E&&"Gecko"==ia.product}var I=D,J=F,ja=E;function K(){var a=n.document;return a?a.documentMode:void 0}var L;
a:{var M="",N;if(C&&n.opera)var O=n.opera.version,M="function"==typeof O?O():O;else if(J?N=/rv\:([^\);]+)(\)|;)/:I?N=/MSIE\s+([^\);]+)(\)|;)/:ja&&(N=/WebKit\/(\S+)/),N)var P=N.exec(G()),M=P?P[1]:"";if(I){var Q=K();if(Q>parseFloat(M)){L=String(Q);break a}}L=M}var R={};
function S(a){if(!R[a]){for(var b=0,c=String(L).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",w=d[e]||"",ka=RegExp("(\\d*)(\\D*)","g"),la=RegExp("(\\d*)(\\D*)","g");do{var l=ka.exec(g)||["","",""],m=la.exec(w)||["","",""];if(0==l[0].length&&0==m[0].length)break;b=((0==l[1].length?0:parseInt(l[1],10))<(0==m[1].length?0:parseInt(m[1],10))?-1:(0==l[1].length?0:parseInt(l[1],10))>
(0==m[1].length?0:parseInt(m[1],10))?1:0)||((0==l[2].length)<(0==m[2].length)?-1:(0==l[2].length)>(0==m[2].length)?1:0)||(l[2]<m[2]?-1:l[2]>m[2]?1:0)}while(0==b)}R[a]=0<=b}}var T=n.document,U=!T||!I?void 0:K()||("CSS1Compat"==T.compatMode?parseInt(L,10):5);var ma=!I||I&&9<=U;!J&&!I||I&&I&&9<=U||J&&S("1.9.1");I&&S("9");function na(a,b){var c;c=a.className;c=s(c)&&c.match(/\S+/g)||[];for(var d=ha(arguments,1),f=c.length+d.length,e=c,g=0;g<d.length;g++)0<=A(e,d[g])||e.push(d[g]);a.className=c.join(" ");return c.length==f};function V(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var W="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function oa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<W.length;e++)c=W[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function pa(a){var b,c,d,f;b=document;if(b.querySelectorAll&&b.querySelector&&a)return b.querySelectorAll(""+(a?"."+a:""));if(a&&b.getElementsByClassName){var e=b.getElementsByClassName(a);return e}e=b.getElementsByTagName("*");if(a){f={};for(c=d=0;b=e[c];c++){var g=b.className;"function"==typeof g.split&&0<=A(g.split(/\s+/),a)&&(f[d++]=b)}f.length=d;return f}return e}
function qa(a,b){V(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in X?a.setAttribute(X[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var X={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function ra(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!ma&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',y(g.name),'"');if(g.type){e.push(' type="',y(g.type),'"');var w={};oa(w,g);delete w.type;g=w}e.push(">");e=e.join("")}e=f.createElement(e);g&&(s(g)?e.className=g:"array"==q(g)?na.apply(h,[e].concat(g)):qa(e,g));2<d.length&&sa(f,e,d);return e}
function sa(a,b,c){function d(c){c&&b.appendChild(s(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(r(e)&&!(t(e)&&0<e.nodeType)){var g;a:{if(e&&"number"==typeof e.length){if(t(e)){g="function"==typeof e.item||"string"==typeof e.item;break a}if("function"==q(e)){g="function"==typeof e.item;break a}}g=k}B(g?ga(e):e,d)}else d(e)}}function ta(a){return ua(a,function(a){return"A"==a.nodeName&&!0})}function ua(a,b){for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return h};function Y(a,b){this.d=a;this.a=b;this.src=b.src;this.type=b.type;this.g=b.cat}function Z(a,b){switch(a){case "floodlight":var c=1E13*(Math.random()+""),d="";V(b,function(a,g){if("ord"==g){var f=y(b.ord);c="1"==f?f+";num="+c:f}else f=y(g)+"="+y(a)+";",d+=f});var f=ra("iframe",{src:fa("//fls.doubleclick.net/activityi;",d,"ord=",c,"?"),width:1,height:1,style:"display: none;"});document.body.appendChild(f)}}
Y.prototype.c=function(a,b){a=s(a)?document.getElementById(a):a;1==a.nodeType&&"A"==a.tagName&&b?$(a,this.f,this):$(a,this.b,this)};Y.prototype.b=function(){Z(this.d,this.a)};Y.prototype.f=function(a){Z(this.d,this.a);a=a||window.event;var b=a.currentTarget||a.srcElement;"A"!=b.tagName&&(b=ta(b));a&&("click"==a.type&&b&&b.href)&&(a.preventDefault?a.preventDefault():a.returnValue=k,setTimeout(function(){window.top.location=b.href},1E3),this.h=b.href)};
Y.prototype.e=function(a,b){var c=pa(a);B(c,function(a){this.c(a,b)},this)};function $(a,b,c){c&&(b=x(b,c));a.addEventListener?a.addEventListener("click",b,k):a.attachEvent&&a.attachEvent("onclick",b)}p("gweb.analytics.DoubleTrack",Y);p("gweb.analytics.DoubleTrack.track",Z);Y.prototype.track=Y.prototype.b;Y.prototype.trackClass=Y.prototype.e;Y.prototype.trackElement=Y.prototype.c;
})()